on:
  push:
    branches:
      - 'feature/*'

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set pull request description
        run: |
          echo "::set-env name=PR_BODY::$(cat .github/PULL_REQUEST_TEMPLATE.md)"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Pull Request Title
          body: ${{ env.PR_BODY }}
          branch: develop
          base: main


