on:
  push:
    branches:
      - 'feature/*'

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set pull request description
        run: |
          echo "${{ steps.read_template.outputs.template }}" >> $GITHUB_WORKSPACE/pr_template.md

      - name: Read pull request template
        id: read_template
        run: |
          echo "::set-output name=template::$(cat .github/PULL_REQUEST_TEMPLATE.md)"

      - name: Update pull request description
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            const template = fs.readFileSync(`${process.env.GITHUB_WORKSPACE}/pr_template.md`, 'utf8');
            const pullRequestNumber = context.payload.pull_request.number;
            if (pullRequestNumber) {
              github.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pullRequestNumber,
                body: template
              });
            }
          token: ${{ secrets.GITHUB_TOKEN }}
