on:
  push:
    branches:
      - 'feature/*'

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set pull request description
        run: |
          echo "${{ steps.read_template.outputs.template }}" >> pr_template.md

      - name: Read pull request template
        id: read_template
        run: |
          echo "::set-output name=template::$(cat .github/PULL_REQUEST_TEMPLATE.md)"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Pull Request Title
          body: ${{ steps.read_template.outputs.template }}
          branch: develop
          base: main



